# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac326662706c53d9192c483022a20048824d25b22d253a8287229b6941c43eb97868902ef82874daf31a6e53da9bae81f23b9bc4ac8735ce94908d4ad26fbb10

test:
  secret_key_base: b32b74d3d90cd40c357662c8003c183b1415b39728d7ccb2550b104f824d55d51c4ed1b1cbe413d0eb41defbb03ee6b1bb183b8acb04541fd6e84c9d6dbf2340

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
